export const leaveArray = [
    {
        type: 'Half',
        days: 1,
        date: '11-05-2024',
        status: 'paid',
        pm_approval: 'approved',
        hr_approval: 'approved',
        temp: 'yes'
    },
    {
        type: 'Full',
        days: 1,
        date: '19-06-2024',
        status: 'paid',
        pm_approval: 'approved',
        hr_approval: 'approved',
    },
    {
        type: 'Half',
        days: 1,
        date: '10-04-2024',
        status: 'Paid',
        pm_approval: 'Rejected',
        hr_approval: 'Rejected',
    },
    {
        type: 'Half',
        days: 1,
        date: '11-05-2024',
        status: 'Paid',
        pm_approval: 'approved',
        hr_approval: 'approved',
    },
    {
        type: 'Half',
        days: 1,
        date: '11-05-2024',
        status: 'Paid',
        pm_approval: 'Rejected',
        hr_approval: 'Rejected',
    },
    {
        type: 'Half',
        days: 1,
        date: '11-05-2024',
        status: 'Paid',
        pm_approval: 'approved',
        hr_approval: 'approved',
    },
    {
        type: 'Half',
        days: 1,
        date: '11-05-2024',
        status: 'Paid',
        pm_approval: 'approved',
        hr_approval: 'approved',
    },
    {
        type: 'Full',
        days: 1,
        date: '11-05-2024',
        status: 'Paid',
        pm_approval: 'Rejected',
        hr_approval: 'Rejected',
    },
    {
        type: 'Half',
        days: 1,
        date: '11-05-2024',
        status: 'Paid',
        pm_approval: 'approved',
        hr_approval: 'approved',
    },
    {
        type: 'Half',
        days: 1,
        date: '11-05-2024',
        status: 'Paid',
        pm_approval: 'approved',
        hr_approval: 'approved',
    },
    {
        type: 'Half',
        days: 1,
        date: '11-05-2024',
        status: 'Paid',
        pm_approval: 'approved',
        hr_approval: 'approved',
    },
    {
        type: 'Half',
        days: 1,
        date: '11-05-2024',
        status: 'Paid',
        pm_approval: 'approved',
        hr_approval: 'approved',
    },
];